In [5]:
import numpy as np


In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])
arr1, arr2

(array([1, 2, 3, 4]), array([10, 20, 30, 40]))

In [3]:
np.concatenate((arr1, arr2))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [4]:
arr3 = np.arange(1, 10).reshape((3,3))
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr4 = np.arange(2, 11).reshape(3,3)
arr4

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [9]:
np.concatenate((arr3,arr4), axis = 1)   #Axis are rowwise or columnwise : 1 is column, 0 is row

array([[ 1,  2,  3,  2,  3,  4],
       [ 4,  5,  6,  5,  6,  7],
       [ 7,  8,  9,  8,  9, 10]])

In [10]:
np.concatenate((arr3,arr4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
np.vstack((arr3,arr4))    #Vertically

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [12]:
np.hstack((arr3,arr4))   #Horizontally

array([[ 1,  2,  3,  2,  3,  4],
       [ 4,  5,  6,  5,  6,  7],
       [ 7,  8,  9,  8,  9, 10]])

In [14]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.slpit(arr3,3, axis=1)

AttributeError: module 'numpy' has no attribute 'slpit'

In [39]:
arr15 = np.arange(1,10).reshape(3,3)
arr15

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr25 = np.arange(2,11).reshape(3,3)
arr25

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [41]:
np.concatenate((arr15, arr25), axis = 1)

array([[ 1,  2,  3,  2,  3,  4],
       [ 4,  5,  6,  5,  6,  7],
       [ 7,  8,  9,  8,  9, 10]])

In [43]:
np.concatenate((arr15,arr25))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [52]:
np.vstack((arr15, arr25))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
np.hstack((arr15, arr25))

array([[ 1,  2,  3,  2,  3,  4],
       [ 4,  5,  6,  5,  6,  7],
       [ 7,  8,  9,  8,  9, 10]])