In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1, 18, 2).reshape(3,3)
arr1

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [3]:
arr2 = np.arange(2, 19, 2).reshape(3,3)
arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### Add

In [4]:
arr1 + arr2

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

### Dot


In [10]:
np.dot(arr1, arr2)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [13]:
np.max(arr1)

np.int64(17)

In [14]:
np.max(arr2)

np.int64(18)

In [16]:
np.min(arr1)

np.int64(1)

In [17]:
np.sum(arr1)

np.int64(81)

In [18]:
np.sum(arr2)

np.int64(90)

In [19]:
np.argmax(arr1)        # Max + index

np.int64(8)

In [20]:
np.argmin(arr1)     #min + index

np.int64(0)

In [21]:
np.mean(arr1)      # Average

np.float64(9.0)

In [22]:
np.sqrt(arr1)     # Square Root

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [23]:
np.exp(arr1)     #e**1, e**2, e**3

array([[2.71828183e+00, 2.00855369e+01, 1.48413159e+02],
       [1.09663316e+03, 8.10308393e+03, 5.98741417e+04],
       [4.42413392e+05, 3.26901737e+06, 2.41549528e+07]])

In [24]:
np.std(arr1)

np.float64(5.163977794943222)

In [25]:
np.log(arr1)

array([[0.        , 1.09861229, 1.60943791],
       [1.94591015, 2.19722458, 2.39789527],
       [2.56494936, 2.7080502 , 2.83321334]])

In [26]:
np.log10(arr1)     # log to the base 10

array([[0.        , 0.47712125, 0.69897   ],
       [0.84509804, 0.95424251, 1.04139269],
       [1.11394335, 1.17609126, 1.23044892]])