In [4]:
import numpy as np

In [5]:
np.random.random()

0.015787327655003902

In [6]:
np.random.rand(3, 4)    #0,  1

array([[0.32198006, 0.46195223, 0.47663985, 0.61485597],
       [0.08174445, 0.94705102, 0.68092128, 0.79722158],
       [0.08213864, 0.66201539, 0.52313083, 0.02725513]])

In [7]:
np.random.randn(10)    #Bell curve

array([ 1.87350771,  0.04055755, -0.9586367 ,  0.58523896,  0.61932135,
       -0.32576116,  0.3427973 ,  0.20896248,  0.11546763,  0.80659143])

In [10]:
np.random.choice([1,2,3,4,5,6], 2)

array([2, 5])

In [11]:
arr = np.array([1, 2, 3, 4, 5])
np.random.permutation(arr)

array([1, 2, 3, 5, 4])